<div class="modal fade custom-modal component-modal" id="addComponentModal" tabindex="-1"
     aria-labelledby="bulkModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5 mb-0" id="bulkModalLabel">Add Component</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="d-flex align-items-start">

                    <input type="hidden" id="component_id" name="component_id">

                    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        <button class="nav-link active" id="about_tab" data-bs-toggle="pill"
                                data-bs-target="#about_content" type="button" role="tab" aria-controls="about_content"
                                aria-selected="true">ABOUT
                        </button>
                        <button class="nav-link" id="medium_tab" data-bs-toggle="pill" data-bs-target="#medium_content"
                                type="button" role="tab" aria-controls="medium_content" aria-selected="false">MEDIUM
                        </button>
                        <button class="nav-link" id="measurement_tab" data-bs-toggle="pill"
                                data-bs-target="#measurement_content" type="button" role="tab"
                                aria-controls="measurement_content" aria-selected="false">MEASUREMENT
                        </button>
                        <button class="nav-link" id="signature_tab" data-bs-toggle="pill"
                                data-bs-target="#signature_content" type="button" role="tab"
                                aria-controls="signature_content" aria-selected="false">SIGNATURE & INSCRIPTIONS
                        </button>
                        <button class="nav-link" id="location_tab" data-bs-toggle="pill"
                                data-bs-target="#location_content" type="button" role="tab"
                                aria-controls="location_content" aria-selected="false">LOCATION
                        </button>
                    </div>
                    <div class="tab-content component-form" id="v-pills-tabContent">
                        <div class="tab-pane fade show active" id="about_content" role="tabpanel"
                             aria-labelledby="about_tab" tabindex="0">
                            <form class="popup-form formFieldInput" id="about-form">
                                <input type="hidden" name="cover_image"/>
                                <div class="mb-5">
                                    <div class="form-group mb-3 singleUploadImage">
                                        <label for="formFile" class="form-label"></label>
                                        <div class="mb-3" id="drag_upload">
                                            <input type="file" name="cover_image_file" id="cover_image"  accept="image/*"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="asign_no" class="form-label">Asign Object Number</label>
                                    <input type="text" class="form-control" id="asign_no" name="asign_no" disabled
                                           placeholder="This will be auto-generated by Asign.">
                                </div>
                                <div class="mb-5">
                                    <label for="accession_no" class="form-label">Accession Number</label>
                                    <input type="text" class="form-control" id="accession_no" name="accession_no"
                                           placeholder="Enter Accession Number">
                                </div>
                                <div class="mb-3 text-end">
                                    <button type="button" data-bs-dismiss="modal" class="btn cancel-btn mx-2">
                                        Cancel
                                    </button>
                                    <button type="submit" class="btn apply-btn">Save</button>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane fade" id="medium_content" role="tabpanel" aria-labelledby="medium_tab"
                             tabindex="0">
                            <form class="popup-form formFieldInput" id="medium-form">
                                <div class="mb-3">
                                    <label for="medium" class="form-label">Medium</label>
                                    <div class="w100Select">
                                        <span class="grey">
                                            <select id="medium" data-placeholder="Select Medium"
                                                class="form-select select2Box" name="mediums[]" multiple>
                                                @foreach($master['medium'] as $medium)
                                                    <option value="{{$medium['id']}}">{{$medium['name']}}</option>
                                                @endforeach
                                            </select>
                                        </span>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="surface" class="form-label">Surface</label>
                                    <div class="w100Select">
                                        <span class="grey">
                                            <select id="surface" data-placeholder="Select Surface" name="surface[]" multiple
                                                    class="form-select select2Box">
                                                @foreach($master['surface'] as $surface)
                                                    <option value="{{$surface['id']}}">{{$surface['name']}}</option>
                                                @endforeach
                                            </select>
                                        </span>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="technique" class="form-label">Technique</label>
                                    <div class="w100Select">
                                        <span class="grey">
                                            <select id="technique" data-placeholder="Select Technique" name="technique_used[]" multiple
                                                    class="form-select select2Box">
                                                @foreach($master['technique'] as $technique)
                                                    <option value="{{$technique['id']}}">{{$technique['name']}}</option>
                                                @endforeach
                                            </select>
                                        </span>
                                    </div>
                                </div>

                                <div class="mb-3 text-end">
                                    <button type="button" data-bs-dismiss="modal" class="btn cancel-btn mx-2">
                                        Cancel
                                    </button>
                                    <button type="submit" class="btn apply-btn">Save</button>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane fade" id="measurement_content" role="tabpanel"
                             aria-labelledby="measurement_tab" tabindex="0">
                            <form class="popup-form formFieldInput" id="measurement-form">
                                <div class="mb-3">
                                    <label for="shape_id" class="form-label">Shape</label>
                                    <div class="w100Select">
                                        <select id="shape_id" name="shape_id" data-placeholder="Select Shape"
                                                class="form-select select2Box">
                                            <option value=""></option>
                                            @foreach($master['shape'] as $shape)
                                                <option value="{{$shape['id']}}">{{$shape['name']}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label for="measurement_type_id" class="form-label">Measurement Type</label>
                                    <div class="w100Select">
                                        <select id="measurement_type_id" name="measurement_type_id"
                                                data-placeholder="Select Measurement Type"
                                                class="form-select select2Box">
                                            <option value=""></option>
                                            @foreach($master['measurement_type'] as $measurement_type)
                                                <option
                                                    value="{{$measurement_type['id']}}">{{$measurement_type['name']}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="mb-3">
                                    <div class="w100Select">
                                        <label for="dimension_size" class="form-label">Dimensions</label>
                                        <select id="dimension_size" name="dimension_size"
                                                data-placeholder="Select Dimensions"
                                                class="form-select select2Box">
                                            <option value=""></option>
                                            <option value="cm">cm</option>
                                            <option value="in">in</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="mb-3">
                                    <label for="width" class="form-label">Width</label>
                                    <input type="text" maxlength="12" class="form-control" id="width" name="width"
                                           placeholder="Enter Width">
                                </div>
                                <div class="mb-3">
                                    <label for="depth" class="form-label">Depth</label>
                                    <input type="text" maxlength="12" class="form-control" id="depth" name="depth"
                                           placeholder="Enter Depth">
                                </div>
                                <div class="mb-3">
                                    <label for="diameter" class="form-label">Diameter</label>
                                    <input type="text" maxlength="12" class="form-control" id="diameter" name="diameter"
                                           placeholder="Enter Diameter">
                                </div>
                                <div class="mb-3">
                                    <label for="weight" class="form-label">Weight</label>
                                    <input type="text" maxlength="12" class="form-control" id="weight" name="weight"
                                           placeholder="Enter Weight">
                                </div>
                                <div class="mb-3 text-end">
                                    <button type="button" data-bs-dismiss="modal"
                                            class="btn cancel-btn mx-2">Cancel
                                    </button>
                                    <button type="submit" class="btn apply-btn">Save</button>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane fade" id="signature_content" role="tabpanel"
                             aria-labelledby="signature_tab" tabindex="0">
                            <form class="popup-form formFieldInput" id="signature-form">

                                <div class="mb-3">
                                    <div class="w100Select">
                                        <label for="is_signature" class="form-label">Signature</label>
                                        <select id="is_signature" name="is_signature"
                                                data-placeholder="Select Signature"
                                                class="form-select select2Box">
                                            <option value=""></option>
                                            <option value="1">Yes</option>
                                            <option value="0" selected>No</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="mb-3" id="signatureDiv" style="display: none">
                                    <label for="signature" class="form-label">Signature</label>
                                    <input type="text" class="form-control" id="signature" name="signature"
                                           placeholder="Enter Signature">
                                </div>

                                <div class="mb-3">
                                    <div class="w100Select">
                                        <label for="is_inscription" class="form-label">Inscription</label>
                                        <select id="is_inscription" name="is_inscription"
                                                data-placeholder="Select Inscription"
                                                class="form-select select2Box">
                                            <option value=""></option>
                                            <option value="1">Yes</option>
                                            <option value="0" selected>No</option>
                                        </select>
                                    </div>
                                </div>

                                <div id="inscriptionDiv" style="display: none">
                                    <div class="mb-3">
                                        <label for="verso_inscription" class="form-label">Verso</label>
                                        <input type="text" class="form-control" id="verso_inscription"
                                               name="verso_inscription"
                                               placeholder="Enter Verso">
                                    </div>
                                    <div class="mb-3">
                                        <label for="recto_inscription" class="form-label">Recto</label>
                                        <input type="text" class="form-control" id="recto_inscription"
                                               name="recto_inscription"
                                               placeholder="Enter Recto">
                                    </div>
                                    <div class="mb-3">
                                        <label for="base_inscription" class="form-label">Base</label>
                                        <input type="text" class="form-control" id="base_inscription"
                                               name="base_inscription"
                                               placeholder="Enter Base">
                                    </div>
                                </div>

                                <div class="mb-3 text-end">
                                    <button type="button" data-bs-dismiss="modal" class="btn cancel-btn mx-2">Cancel
                                    </button>
                                    <button type="submit" class="btn apply-btn">Save</button>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane fade" id="location_content" role="tabpanel" aria-labelledby="location_tab"
                             tabindex="0">
                            <form class="popup-form formFieldInput" id="component-location-form">
                                <div class="mb-3">
                                    <label for="location_as" class="form-label">Save Location</label>
                                    <input type="text" class="form-control" id="location_as" name="location_as"
                                           placeholder="Enter Save Location">
                                </div>

                                <div class="mb-3">
                                    <label for="sub_location" class="form-label">Sub Location</label>
                                    <input type="text" class="form-control" id="sub_location" name="sub_location" maxlength="1000"
                                           placeholder="Enter Sub Location">
                                </div>

                                <div class="mb-3">
                                    <label for="address_line1" class="form-label">Address</label>
                                    <input type="text" class="form-control" id="address_line1" name="address_line1" maxlength="1000"
                                           placeholder="Enter Address Line1">
                                </div>

                                <div class="mb-3">
                                    <label for="address_line2" class="form-label">Address</label>
                                    <input type="text" class="form-control" id="address_line2" name="address_line2"  maxlength="1000"
                                           placeholder="Enter Address Line2">
                                </div>

                                <div class="mb-3">
                                    <label for="country_id" class="form-label">Country</label>
                                    <div class="w100Select">
                                        <select id="country_id" name="country_id" data-placeholder="Select Country"
                                                class="form-select select2Box">
                                            <option value=""></option>
                                            @foreach($master['country'] as $country)
                                                <option
                                                    value="{{$country['id']}}" {{$country['id'] == '102' ? 'selected' : ''}}>{{$country['name']}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="mb-3">
                                    <label for="state_id" class="form-label">State</label>
                                    <div class="w100Select">
                                        <select id="state_id" name="state_id" data-placeholder="Select State"
                                                class="form-select select2Box">
                                            <option value=""></option>
                                            @foreach($master['state'] as $state)
                                                <option value="{{$state['id']}}">{{$state['name']}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="mb-3">
                                    <label for="city" class="form-label">City</label>
                                    <input type="text" class="form-control" id="city" name="city" maxlength="50"
                                           placeholder="Enter City">
                                </div>

                                <div class="mb-5">
                                    <label for="pin_code" class="form-label">Pincode</label>
                                    <input type="text" class="form-control" id="pin_code" name="pin_code" maxlength="10"
                                           placeholder="Enter Pincode">
                                </div>

                                <div class="mb-3 text-end">
                                    <button type="button" data-bs-dismiss="modal"
                                            class="btn cancel-btn mx-2">Cancel
                                    </button>
                                    <button type="submit" class="btn apply-btn">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
